ALTER TABLE clients
  ADD COLUMN IF NOT EXISTS type_client TEXT NOT NULL DEFAULT 'PRO',
  ADD COLUMN IF NOT EXISTS raison_sociale TEXT,
  ADD COLUMN IF NOT EXISTS siret TEXT,
  ADD COLUMN IF NOT EXISTS prenom TEXT,
  ADD COLUMN IF NOT EXISTS nom TEXT,
  ADD COLUMN IF NOT EXISTS email TEXT,
  ADD COLUMN IF NOT EXISTS telephone TEXT,
  ADD COLUMN IF NOT EXISTS actif BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE clients
  ADD COLUMN IF NOT EXISTS adresse_ligne1 TEXT,
  ADD COLUMN IF NOT EXISTS adresse_ligne2 TEXT,
  ADD COLUMN IF NOT EXISTS code_postal TEXT,
  ADD COLUMN IF NOT EXISTS ville TEXT,
  ADD COLUMN IF NOT EXISTS pays TEXT;
