apiVersion: apps/v1
kind: Deployment
metadata:
  name: clm-front-admin
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: clm-front-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clm-front-admin
  template:
    metadata:
      labels:
        app: clm-front-admin
    spec:
      containers:
        - name: clm-front-admin
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: production
          envFrom:
            - configMapRef:
                name: clm-front-admin-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "150m"
            limits:
              memory: "256Mi"
              cpu: "250m"
